2019-05-16 10:53:43,630 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:184] - INFO: The screen size: 720x1280
2019-05-16 10:54:04,382 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:185] - INFO: The screen size: 720x1280
2019-05-16 11:01:47,553 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:181] - INFO: The screen size: 720x1280
2019-05-16 11:03:02,422 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:181] - INFO: The screen size: 720x1280
2019-05-16 11:08:40,282 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:181] - INFO: The screen size: 720x1280
2019-05-16 11:09:03,306 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:181] - INFO: The screen size: 720x1280
2019-05-16 11:10:00,186 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:181] - INFO: The screen size: 720x1280
2019-05-16 11:11:02,116 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:181] - INFO: The screen size: 720x1280
2019-05-16 11:11:03,212 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:202] - ERROR: Launch the VR failed, Error: Activity class {com.gm.vr/com.gm.vr.PTTActivity} does not exist.
2019-05-16 11:22:14,766 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:233] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i sample_audio.wav -g ./res/grammarList.txt
2019-05-16 11:22:15,308 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: Audio state changed: Silence.
2019-05-16 11:22:15,308 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: Audio state changed: Stopped.
2019-05-16 11:22:15,308 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: I guess you said:NONE
2019-05-16 11:22:15,308 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: My confidence is:0
2019-05-16 11:22:15,308 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: 
2019-05-16 11:22:29,563 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:233] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i sample_audio.wav -g ./res/grammarList.txt
2019-05-16 11:25:50,658 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: Audio state changed: Silence.
2019-05-16 11:25:50,658 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: Audio state changed: Stopped.
2019-05-16 11:25:50,658 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: I guess you said:NONE
2019-05-16 11:25:50,658 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: My confidence is:0
2019-05-16 11:25:50,658 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:238] - INFO: 
2019-05-16 11:28:44,968 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:234] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i sample_audio.wav -g ./res/grammarList.txt
2019-05-16 11:28:45,417 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Silence.
2019-05-16 11:28:45,417 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Stopped.
2019-05-16 11:28:45,417 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: I guess you said:NONE
2019-05-16 11:28:45,417 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: My confidence is:0
2019-05-16 11:28:45,417 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: 
2019-05-16 11:34:02,763 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:234] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g ./res/grammarList.txt
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Silence.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Speech.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Speech detected: 00:00:01.8600000.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Guess speech: Audio, confidence: 0.7732304, alternates: 0.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Guess speech: Audio Command, confidence: 0.9281954, alternates: 0.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Guess speech: Audio Command Please, confidence: 0.9406216, alternates: 0.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio signal problem occured: TooSoft, audio position: 00:00:05.0750000, audio level: 0, recognizer pos: 00:00:04.8000000.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Silence.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Recognized: Audio Command Please, confidence: 0.9329299, alternates: 1, audio position: 00:00:01.9700000, audio duration: 00:00:01.8900000.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Stopped.
2019-05-16 11:34:03,193 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: I guess you said:Audio Command Please
2019-05-16 11:34:03,194 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: My confidence is:0.9329299
2019-05-16 11:34:03,194 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: 
2019-05-16 13:57:13,001 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:308] - ERROR: SetupVRENV Error: invalid literal for int() with base 10: 'mic'
2019-05-16 13:57:13,002 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:310] - ERROR: Stack Trace: Traceback (most recent call last):
  File "D:/sxz/practice/py3-practice/src/SetupVREnv.py", line 288, in <module>
    mic_volume = int(cfg["MICROPHONE"])
ValueError: invalid literal for int() with base 10: 'mic'

2019-05-16 13:59:29,023 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:43] - INFO: Loading dll...
2019-05-16 13:59:35,907 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:57] - INFO: The default microphone volume is set to 60
2019-05-16 13:59:35,909 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:70] - INFO: The default speaker volume is set to 70
2019-05-16 13:59:35,909 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:79] - INFO: tuning the csm volume....
2019-05-16 13:59:35,966 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:94] - ERROR: Tune CSM volume failed, error: no devices/emulators found

2019-05-16 13:59:53,567 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:234] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g ./res/grammarList.txt
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Silence.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Speech.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Speech detected: 00:00:01.8600000.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Guess speech: Audio, confidence: 0.7732304, alternates: 0.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Guess speech: Audio Command, confidence: 0.9281954, alternates: 0.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Guess speech: Audio Command Please, confidence: 0.9406216, alternates: 0.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio signal problem occured: TooSoft, audio position: 00:00:05.0750000, audio level: 0, recognizer pos: 00:00:04.8000000.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Silence.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Recognized: Audio Command Please, confidence: 0.9329299, alternates: 1, audio position: 00:00:01.9700000, audio duration: 00:00:01.8900000.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: Audio state changed: Stopped.
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: I guess you said:Audio Command Please
2019-05-16 13:59:54,085 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: My confidence is:0.9329299
2019-05-16 13:59:54,086 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:239] - INFO: 
2019-05-16 14:19:23,780 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:232] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g "./res/grammarList.txt"
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Audio state changed: Silence.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Audio state changed: Speech.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Speech detected: 00:00:01.8600000.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Guess speech: Audio, confidence: 0.7732304, alternates: 0.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Guess speech: Audio Command, confidence: 0.9281954, alternates: 0.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Guess speech: Audio Command Please, confidence: 0.9406216, alternates: 0.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Audio signal problem occured: TooSoft, audio position: 00:00:05.0750000, audio level: 0, recognizer pos: 00:00:04.8000000.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Audio state changed: Silence.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Recognized: Audio Command Please, confidence: 0.9329299, alternates: 1, audio position: 00:00:01.9700000, audio duration: 00:00:01.8900000.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: Audio state changed: Stopped.
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: I guess you said:Audio Command Please
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: My confidence is:0.9329299
2019-05-16 14:19:24,172 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:237] - INFO: 
2019-05-16 14:36:01,580 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:232] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin11.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g "./res/grammarList.txt"
2019-05-16 14:36:01,601 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:251] - ERROR: 'C:\cats-node\prod\speech-recognize/SpeechRecognizeBin11.exe' is not recognized as an internal or external command,
operable program or batch file.

2019-05-16 14:36:16,946 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:232] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin11.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g "./res/grammarList.txt"
2019-05-16 14:47:44,908 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:232] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g "./res/grammarList.txt"
2019-05-16 14:47:45,495 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:241] - INFO: I guess you said:Audio Command Please
2019-05-16 14:54:22,599 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:42] - INFO: Loading dll...
2019-05-16 14:54:29,443 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:56] - INFO: The default microphone volume is set to 60
2019-05-16 14:54:29,445 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:69] - INFO: The default speaker volume is set to 70
2019-05-16 14:54:29,445 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:78] - INFO: tuning the csm volume....
2019-05-16 14:54:29,501 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:93] - ERROR: Tune CSM volume failed, error: no devices/emulators found

2019-05-16 14:55:12,869 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:42] - INFO: Loading dll...
2019-05-16 14:55:19,572 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:232] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g "./res/grammarList.txt"
2019-05-16 14:55:19,959 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:241] - INFO: I guess you said:Audio Command Please
2019-05-16 15:26:53,435 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:42] - INFO: Loading dll...
2019-05-16 15:27:00,295 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:233] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g "./res/grammarList.txt"
2019-05-16 15:27:00,746 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:242] - INFO: I guess you said:Audio Command Please
2019-05-16 15:27:00,746 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:302] - INFO: Setup VR Env successfully, tune times:1
2019-05-16 15:29:02,721 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:42] - INFO: Loading dll...
2019-05-16 15:29:09,534 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:344] - ERROR: SetupVRENV Error: [Errno 22] Invalid argument: '"./res/audio.wav"'
2019-05-16 15:29:09,537 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:346] - ERROR: Stack Trace: Traceback (most recent call last):
  File "D:/sxz/practice/py3-practice/src/SetupVREnv.py", line 341, in <module>
    main(cfg)
  File "D:/sxz/practice/py3-practice/src/SetupVREnv.py", line 298, in main
    recognize_result, confidence = loop(mic_volume, speaker_volume, csm_volume, cfg)
  File "D:/sxz/practice/py3-practice/src/SetupVREnv.py", line 272, in loop
    play(cfg["PLAY_AUDIO"])
  File "D:/sxz/practice/py3-practice/src/SetupVREnv.py", line 144, in play
    wf = wave.open(audio_file, 'rb')
  File "C:\Program Files (x86)\Python\Python35\lib\wave.py", line 499, in open
    return Wave_read(f)
  File "C:\Program Files (x86)\Python\Python35\lib\wave.py", line 159, in __init__
    f = builtins.open(f, 'rb')
OSError: [Errno 22] Invalid argument: '"./res/audio.wav"'

2019-05-16 15:29:41,943 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:42] - INFO: Loading dll...
2019-05-16 15:29:48,791 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:154] - INFO: Playing the audio: ./res/audio.wav
2019-05-16 15:29:49,757 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:167] - INFO: Done playing
2019-05-16 15:29:54,861 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:140] - INFO: Done recording: recorded_audio.wav
2019-05-16 15:29:54,861 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:233] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g ./res/grammarList.txt
2019-05-16 15:29:55,239 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:242] - INFO: I guess you said:Audio Command Please
2019-05-16 15:29:55,239 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:302] - INFO: Setup VR Env successfully, tune times:1
2019-05-16 15:34:14,819 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:42] - INFO: Loading dll...
2019-05-16 15:34:21,519 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:154] - INFO: Playing the audio: ./res/audio.wav
2019-05-16 15:34:22,481 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:167] - INFO: Done playing
2019-05-16 15:34:27,529 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:140] - INFO: Done recording: recorded_audio.wav
2019-05-16 15:34:27,529 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:233] - INFO: To execute cmd: C:\cats-node\prod\speech-recognize/SpeechRecognizeBin.exe -d -i D:\cats\bugs\setup\SetupVREnv\sample_audio.wav -g ./res/grammarList.txt
2019-05-16 15:34:28,006 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:242] - INFO: I guess you said:Audio Command Please
2019-05-16 15:34:28,006 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:302] - INFO: Setup VR Env successfully, tune times:1
2019-05-16 15:36:14,290 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:344] - ERROR: SetupVRENV Error: invalid literal for int() with base 10: 'mix'
2019-05-16 15:36:14,291 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:346] - ERROR: Stack Trace: Traceback (most recent call last):
  File "D:/sxz/practice/py3-practice/src/SetupVREnv.py", line 341, in <module>
    main()
  File "D:/sxz/practice/py3-practice/src/SetupVREnv.py", line 287, in main
    mic_volume = int(cfg["MICROPHONE"])
ValueError: invalid literal for int() with base 10: 'mix'

2019-05-16 16:12:26,765 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:42] - INFO: Loading dll...
2019-05-16 16:12:33,585 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:56] - INFO: The default microphone volume is set to 60
2019-05-16 16:12:33,588 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:69] - INFO: The default speaker volume is set to 70
2019-05-16 16:12:33,588 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:78] - INFO: tuning the csm volume....
2019-05-16 16:12:33,643 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:94] - ERROR: Tune CSM volume failed, error: no devices/emulators found

2019-05-17 09:57:49,043 - D:/sxz/practice/py3-practice/src/test_csm_volume.py[line:158] - ERROR: Fail to execute cmd: adb shell wm size,
 error: no devices/emulators found

2019-05-17 09:58:12,696 - D:/sxz/practice/py3-practice/src/test_csm_volume.py[line:158] - ERROR: Fail to execute cmd: adb shell wm size, error: no devices/emulators found

2019-05-17 09:58:23,863 - D:/sxz/practice/py3-practice/src/test_csm_volume.py[line:158] - ERROR: Fail to execute cmd: adb shell wm size, error: no devices/emulators found

2019-05-17 18:12:03,414 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:59] - INFO: Loading dll...
2019-05-17 18:12:10,621 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:389] - INFO: ******************************
2019-05-17 18:12:10,621 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:390] - INFO: The VR env can not work.
2019-05-17 18:12:10,621 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:391] - INFO: ******************************
2019-05-17 18:13:37,737 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:59] - INFO: Loading dll...
2019-05-17 18:13:44,609 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:389] - INFO: ******************************
2019-05-17 18:13:44,609 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:390] - INFO: The VR env can not work.
2019-05-17 18:13:44,609 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:391] - INFO: ******************************
2019-05-17 18:20:59,073 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:59] - INFO: Loading dll...
2019-05-17 18:21:05,891 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:389] - INFO: ******************************
2019-05-17 18:21:05,891 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:390] - INFO: The VR env can not work.
2019-05-17 18:21:05,891 - D:/sxz/practice/py3-practice/src/SetupVREnv.py[line:391] - INFO: ******************************
